# Generated by Django 4.2.1 on 2023-08-12 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('desc', models.CharField(max_length=250)),
                ('years', models.IntegerField()),
                ('img', models.ImageField(blank=True, null=True, upload_to='img')),
            ],
        ),
    ]
